name: Bug report
description: Template for bug reports
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: input
    attributes:
      label: Location
      description: URL of the specific page where the problem occurs
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: provide steps to reproduce the problem
      placeholder: If the problem can't be reproduced, it can't be fixed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
  - type: dropdown
    attributes:
      label: Browser
      description: Which browser are you using
      options:
        - Chrome
        - Firefox
        - Edge
        - Other (unsupported)
    validations:
      required: true
  - type: input
    attributes:
      label: Extension version
      description: Which extension version you are using
