name: Feature request
description: Template for feature requests
title: '[Feature]: <title>'
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of your feature request
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
